version: 2.1

orbs:
  python: circleci/python@0.3.0

executors:
  uml-executor:
    docker:
      - image: python:3.7.3-stretch

jobs:
  build:
    executor: uml-executor
    steps:
      - checkout
      - python/load-cache
      - python/install-deps

      - run:
          name: install-hadolint
          command: |
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            chmod +x /bin/hadolint

      - python/save-cache
        
      - run:
          name: run-linters
          command: |
            export PATH=$HOME/.local/bin:$PATH
            make lint

workflows:
  main:
    jobs:
      - build