version: 2.1

orbs:
  python: circleci/python@0.3.0

parameters:
  tag:
    default: '3.7'
    description: The `cimg/python` Docker image version tag.
    type: string

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps

      - run:
          name: install-hadolint
          command: |
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            sudo chmod +x /bin/hadolint

      - python/save-cache
        
      - run:
          name: run-linters
          command: make lint

workflows:
  main:
    jobs:
      - build