version: 2.1

orbs:
  python: circleci/python@0.3.0

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          name: install-scipy
          command: |
            wget https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh
            bash Anaconda3-2020.02-Linux-x86_64.sh
            conda install scipy

      - python/install-deps

      - run:
          name: install-hadolint
          command: |
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint

      - python/save-cache
        
      - run:
          name: run-hadolint
          command: make lint

workflows:
  main:
    jobs:
      - build