apiVersion: apps/v1
kind: Deployment
metadata:
  name: uml-deployment
spec:
  selector:
    matchLabels:
      app: uml
  replicas: 2
  template:
    metadata:
      labels:
        app: uml
    spec:
      containers:
        - name: uml
          image: agmeteor/uml:latest
          ports:
            - containerPort: 80